[technote]
id = "SQR-112"
series_id = "SQR"
canonical_url = "https://sqr-112.lsst.io"
github_url = "https://github.com/lsst-sqre/sqr-112"
github_default_branch = "main"
date_created = 2026-02-10T16:51:56Z
organization.name = "NSF-DOE Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Jonathan"
name.family = "Sick"
internal_id = "sickj"
orcid = "https://orcid.org/0000-0003-3001-676X"
[[technote.authors.affiliations]]
name = "J.Sick Codes Inc."
internal_id = "JSickCodes"
address = "Penetanguishene"
